### ISSUE TITLE
An error has occurred

### ISSUE THREAD

**Issue by SirVirgo** [ManuDash5/Textgen_webui_NEW#1]
After about half an hour, the colab started giving this error and stopped generating text. Restarting the cell didn't help. Of course this can probably be fixed by a complete restart of the colab, but I decided to report this problem. I used SillyTavern with Response Length 200 and Context size 4096, Pygmalion 13B model, no colab pro. 

And thanks also for this colab despite this error it is incredibly cool.

![image](https://github.com/ManuDash5/Textgen_webui_NEW/assets/127517659/208ae727-a49e-4125-a431-d5e6ba3c4092)

**Comment by SirVirgo** [comment]
Hm interesting. I've checked and even a complete restart of the colab doesn't solve the problem. Strange that everything was fine for a while and then all of a sudden the error appears.

**Comment by SirVirgo** [comment]
It seems that if you chat for too long, you get this kind of error

**Comment by umbralogix** [comment]
Same issue, happens quite frequently. The collab is now unusable.

**Comment by ManuDash5** [comment]
Hmm, that error in google points out at the Linux version of running out of memory, yet i don't know, maybe they updated oobabooga, i will look into this but i will say, i can't promise anything, because i don't really know what's happening there, have a nice day everyone!

**Comment by SirVirgo** [comment]
> Same issue, happens quite frequently. The collab is now unusable.

I reduced the context size to 3096 and so far no more errors have occurred. Try this until some other solution is found.

**Comment by ManuDash5** [comment]
I have found something: That error happens because the frontend sends more tokens than the maximum context size, in your frontend lower the context size to about 100 tokens less than what you selected in this colab. I also made the example on the r/pygmalion_ai post. "(if the context size selected is 6144, use 6000 in the frontend; if the context size selected is 4096, use 4000 on the frontend)"
